:mod:`rec_to_nwb.processing.exceptions.corrupted_data_exception`
================================================================

.. py:module:: rec_to_nwb.processing.exceptions.corrupted_data_exception


Module Contents
---------------

.. py:exception:: CorruptedDataException(*args)

   Bases: :class:`rec_to_nwb.processing.exceptions.invalid_exception.InvalidException`

   .. method:: __str__(self)




